services:
  postgres:
    image: postgres:16
    container_name: vacina_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vacina
      POSTGRES_USER: vacina
      POSTGRES_PASSWORD: vacina
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: vacina_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vacina.local
      PGADMIN_DEFAULT_PASSWORD: Admin@123
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  pg_data:
